// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArjXlwmI4goKQQRWjN9yWMjN6cmHru6b8',
    appId: '1:376869536101:web:8df992fb69d0ccf8d0a18c',
    messagingSenderId: '376869536101',
    projectId: 'ecommerceapp-42223',
    authDomain: 'ecommerceapp-42223.firebaseapp.com',
    storageBucket: 'ecommerceapp-42223.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe0dntCBljI-33fsbhP_-2ArhRqqWiAR0',
    appId: '1:376869536101:android:fd783ec59dd6f7e8d0a18c',
    messagingSenderId: '376869536101',
    projectId: 'ecommerceapp-42223',
    storageBucket: 'ecommerceapp-42223.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtYMoznViU9u3oY4Ei86t7wir6fxtYxzU',
    appId: '1:376869536101:ios:c77b8e55b0f71e8cd0a18c',
    messagingSenderId: '376869536101',
    projectId: 'ecommerceapp-42223',
    storageBucket: 'ecommerceapp-42223.firebasestorage.app',
    androidClientId: '376869536101-bs6aaif7h4khnbon604vh5iusp0nstul.apps.googleusercontent.com',
    iosClientId: '376869536101-94fr4cfbeec1h5sjfp6n801kpumgu7go.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArjXlwmI4goKQQRWjN9yWMjN6cmHru6b8',
    appId: '1:376869536101:web:86f4138c29b20037d0a18c',
    messagingSenderId: '376869536101',
    projectId: 'ecommerceapp-42223',
    authDomain: 'ecommerceapp-42223.firebaseapp.com',
    storageBucket: 'ecommerceapp-42223.firebasestorage.app',
  );

}